config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  'home#index'
  get 'users/:id/likes' => 'likes#show'

  resources :meigens do
    collection do
      get 'contentSearch'
      get 'sourceSearch'
      get 'tagSearch'
    end
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update]
  resources :points, only: [:create, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :meigen, counter_cache: :comments_count
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :meigen, counter_cache: :likes_count
  belongs_to :user
end

app/models/meigen.rb
class Meigen < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :points, dependent: :destroy

  mount_uploader :image, ImageUploader
  validates :content, presence: true, uniqueness: true
  validates :source, presence: true

  acts_as_taggable


  scope :contents, -> keyword do
    if keyword.present?
      Meigen.where("content LIKE(?)", "%" + keyword + "%")
    end
  end

  scope :sources, -> keyword do
    if keyword.present?
      Meigen.where("source LIKE(?)", "%" + keyword + "%")
    end
  end

  scope :tags, -> keyword do

      Meigen.joins(:tags).select("meigens.*, tags.name").where("name LIKE(?)", "%" + keyword + "%")

  end


  def like_user(id)
    likes.find_by(user_id: id)
  end
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :user
  belongs_to :meigen

  validates :value, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :email, uniqueness: true, null: false
  validates :name, presence: true, uniqueness: true, null: false

  has_many :meigens
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :points, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.create(comment_params)
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, meigen_id: params[:meigen_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = current_user.likes.create(meigen_id: params[:meigen_id])
  end

  def destroy
    @like = current_user.likes.find_by(meigen_id: params[:meigen_id])
    @meigen = @like.meigen
    @like.destroy
  end

  def show
    likes = Like.where(user_id: current_user.id).order("created_at DESC")
    @meigens = []
    likes.each do |like|
      @meigens << like.meigen
    end
  end

end

app/controllers/meigens_controller.rb
class MeigensController < ApplicationController
  def index
    @meigens = Meigen.includes(:user).order("created_at DESC")
  end

  def new
    @meigen = Meigen.new
  end

  def create
    image = meigen_params[:image] if params[:meigen][:image]

    @meigen = Meigen.new(meigen_params)

    if @meigen.save
      increase_point = current_user.point + 10
      current_user.update(point: increase_point)
      redirect_to("/meigens")
    else
      render("meigens/new")
    end
  end

  def edit
    @meigen = Meigen.find(params[:id])
  end

  def update
    meigen = Meigen.find(params[:id])
    meigen.update(meigen_params) if meigen.user_id == current_user.id
    redirect_to("/meigens/#{params[:id]}")
  end

  def show
    @meigen = Meigen.find(params[:id])
    @comment = Comment.new

    @point = Point.new
    @current_status = Point.where("meigen_id = ? and user_id = ?", @meigen.id, current_user.id)
    @current_status.present? ? @current_point = @current_status[0].value : @current_point = 0

    if current_user.point == 0 && @current_status.empty?
      pull_down_menu_max = 0
    else
      pull_down_menu_max = @current_point + current_user.point

    end

    @num = []
    0.step(pull_down_menu_max, 10) do |i|
      @num << i
    end

    points = Point.includes(:user).where("meigen_id = ?", @meigen.id)
    max = points.maximum(:value)
    @max_point = points.where("value = ?", max)

  end

  def destroy
    meigen = Meigen.find(params[:id])

    meigen.points.each do |point|
      repair = point.user.point + point.value
      point.user.update(point: repair)
    end

    meigen.destroy if meigen.user_id == current_user.id
    redirect_to meigens_path
  end

  def contentSearch
    @meigens = Meigen.contents(params[:keyword])
    respond_to do |format|
      format.html
      format.json
    end
  end

  def sourceSearch
    @source_meigens = Meigen.sources(params[:keyword])
    respond_to do |format|
      format.html
      format.json
    end
  end

  def tagSearch
    @tag_meigens = Meigen.tags(params[:keyword])
    respond_to do |format|
      format.html
      format.json
    end
  end


  private

  def meigen_params
    params.require(:meigen).permit(:content, :scene, :image, :source, :tag_list).merge(user_id: current_user.id)
  end

end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  def create
    #表示中の名言の情報を取得
    meigen = Meigen.find(create_params[:meigen_id])

    # ログインユーザーが対象の投稿にポイントを振っていないか確認(配列取得)
    point = Point.where('user_id = ? and meigen_id = ?', current_user.id, meigen.id)

    if point.present? # ポイントを振っていた場合
      # 現在のポイントを取得する
      # 送った後のポイント = 現在のポイント - 送ったポイント + すでに振っているポイント
      current_point = current_user.point - create_params[:value].to_i + point[0].value

      current_user.update(point: current_point)
      point.update(create_params)
    else # ポイントを振っていない場合
      current_point = current_user.point - create_params[:value].to_i
      Point.create(create_params)
      current_user.update(point: current_point)
    end
    redirect_to meigen_path(meigen.id)
  end


  def show
    points = Point.where(user_id: current_user.id).order("created_at DESC")
    @meigens = []
    points.each do |point|
      @meigens << point.meigen
    end
  end


  private

  def create_params
    params.require(:point).permit(:meigen_id, :value).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @meigens = user.meigens.where(user_id: current_user.id).order("created_at DESC")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/create.js.erb
$(".meigen-show-container__form-box__comment-index").append("<%= j(render partial: 'meigens/comment-view', locals: { comment: @comment }) %>");
$("#comment-area").val('');

var html = `<i class="far fa-comment">
              <%= @comment.meigen.comments_count %>
            </i>`
$("#comment-counter").html(html);

$(".no-comment").remove();

app/views/comments/destroy.js.erb
$(".comment-id-<%= @comment.id %>").remove();

var html = `<i class="far fa-comment">
              <%= @comment.meigen.comments_count %>
            </i>`
$("#comment-counter").html(html);

app/views/home/index.html.haml
.intro-container
  = video_tag 'Time-Lapse-Video-Of-Sunrise-By-The-Sea.webm', autoplay: true, loop: true, muted: true, class: 'intro-container--movie'
  .intro-container__message
    %p 名言を自分のものにする
  = link_to meigens_path do
    .meigen-list-link
      投稿一覧へ

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title 超名言 -名言を自分のものにするアプリ-
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'

  %body
  - if controller.controller_name == "sessions" || controller.controller_name == "registrations" || controller.controller_name == "passwords"
    = yield

  -else
    .header
      .header-nav
        .header-nav__title
          = link_to "超名言", "/"
        - if user_signed_in?
          .header-nav__menu
            %ul
              %li.header-nav__menu--content
                = link_to "マイページ", "/users/#{current_user.id}"
              %li.header-nav__menu--content#modal-open
                検索
              %li.header-nav__menu--content.header-nav__menu--content--small
                = link_to "ログアウト", destroy_user_session_path, method: :delete
              - if controller.action_name != "new"
                %li.header-nav__menu--content.header-nav__menu--content--post-btn
                  = link_to "投稿する", new_meigen_path
              - if controller.controller_name == "home"
                %li.header-nav__menu--content.side-menu-position
                  .fas.fa-angle-double-right
                  = link_to "使い方", "#", class: "js__sideMenuBtn"
              - else
                %li.header-nav__menu--content
                  = link_to "投稿一覧へ", meigens_path

          .side-menu
            .side-menu__header
              %h1 「超名言」って？
              %p 感動、共感、好き・・・そんな名言を投稿できる場所です
              %p 気に入った投稿を集めたり、自分のものにできます
            .side-menu__explanation
            %ul.exp-list
              %li.exp-list-item1
                １．何ができるの？
                %span +
              .exp-list-content1
                %ul
                  %li
                    %p 自分の好きな名言を投稿できます
                  %li
                    %p 内容とその出典(人・本)は必ず入力してください
                  %li
                    %p 内容、出典、タグで投稿の検索できます
                  %li
                    %p マイページで自分の投稿と"いいね"した投稿が見られます
              %li.exp-list-item2
                ２．名言を自分のものにする、って？
                %span +
              .exp-list-content2
                %ul
                  %li
                    %p 「この名言には感動した！」という投稿にポイントを投資することができます。
                  %li
                    %p ポイントを最も振った人がその名言を自分のものにすることができ、ユーザー名が載ります！
                  %li
                    %p アカウントの新規登録時点で100pt、投稿すると10pt獲得できます。残りポイント数はマイページで確認できます。

          .meigen-search-modal
            .meigen-search-modal__overlay
            .meigen-search-modal__content
              .meigen-search-modal__content__header
                %h1 名言を探す
                %input{type: "text", placeholder: "キーワードを入力してください", class: "search-field"}
                %input{type: "text", placeholder: "キーワードを入力してください", class: "dummy-field"}
                .search-close
                  %i.fas.fa-times#modal-close

              .meigen-search-modal__content__result
                %h2 名言
                .meigen-search-modal__content__result__box
                  %ul.search-result1
              .meigen-search-modal__content__result#search-result-center
                %h2 名言の出典
                .meigen-search-modal__content__result__box
                  %ul.search-result2
              .meigen-search-modal__content__result#search-result-right
                %h2 タグ
                .meigen-search-modal__content__result__box
                  %ul.search-result3

          .header-notice
            = notice
          .header-alert
            = alert

        - else
          .header-nav__menu
            %ul
              %li.header-nav__menu--content
                = link_to "超名言って？", "#", class: "js__sideMenuBtn"
              %li.header-nav__menu--content
                = link_to "ログイン", new_user_session_path
              %li.header-nav__menu--content
                = link_to "新規登録", new_user_registration_path

          .side-menu
            .side-menu__header
              %h1 「超名言」って？
              %p 感動、共感、好き・・・そんな名言を投稿できる場所です
              %p 気に入った投稿を集めたり、自分のものにできます
            .side-menu__explanation
            %ul.exp-list
              %li.exp-list-item1
                １．何ができるの？
                %span +
              .exp-list-content1
                %ul
                  %li
                    %p 自分の好きな名言を投稿できます
                  %li
                    %p 内容とその出典(人・本)は必ず入力してください
                  %li
                    %p 内容、出典、タグで投稿の検索できます
                  %li
                    %p マイページで自分の投稿と"いいね"した投稿が見られます
              %li.exp-list-item2
                ２．名言を自分のものにする、って？
                %span +
              .exp-list-content2
                %ul
                  %li
                    %p 「この名言には感動した！」という投稿にポイントを投資することができます。
                  %li
                    %p ポイントを最も振った人がその名言を自分のものにすることができ、ユーザー名が載ります！
                  %li
                    %p アカウントの新規登録時点で100pt、投稿すると10pt獲得できます。残りポイント数はマイページで確認できます。

          .header-notice
            = notice
          .header-alert
            = alert

    = yield

app/views/likes/create.js.erb
$(".like-heart-<%= @like.meigen.id %>").html("<%= j(render partial: 'meigens/like-view', locals: { meigen: @like.meigen }) %>");

app/views/likes/destroy.js.erb
$(".like-heart-<%= @meigen.id %>").html("<%= j(render partial: 'meigens/like-view', locals: { meigen: @meigen }) %>");

app/views/likes/show.html.haml
.wrapper-for-meigen-index
  .my-page-header
    %h1
      = current_user.name
      さんのマイページ
    %ul
      %li
        = link_to "/users/#{current_user.id}" do
          ●投稿一覧
      %li
        ●いいね一覧
      %li#point-column
        = link_to "/points/#{current_user.id}" do
          ●ポイント振った投稿一覧

    .my-page-header__remain-point
      %p
        ポイント残高：
        = current_user.point

  = render partial: "shared/display_products", locals: { meigens: @meigens }

app/views/meigens/_comment-view.html.haml
.meigen-show-container__form-box__comment-index__items{class: "comment-id-#{comment.id}"}
  .meigen-show-container__form-box__comment-index__items__left
    %p
      = comment.user.name
      ：
  .meigen-show-container__form-box__comment-index__items__center
    %p
      = simple_format(comment.content)
  - if comment.user_id == current_user.id
    = link_to meigen_comment_path(comment.meigen_id, comment.id), method: :delete, remote: true, class: "delete-cross" do
      %i.fas.fa-times

app/views/meigens/_like-view.html.haml
- if meigen.like_user(current_user.id)
  = link_to meigen_like_path(meigen, meigen.like_user(current_user.id)), method: :delete, remote: true do
    %i.fas.fa-bullhorn.already-like
  = meigen.likes_count
- else
  = link_to meigen_likes_path(meigen), method: :post, remote: true do
    %i.fas.fa-bullhorn.not-yet-like
  = meigen.likes_count

app/views/meigens/edit.html.haml
= render partial: "shared/input_product", locals: { meigen: @meigen }

app/views/meigens/index.html.haml
.wrapper-for-meigen-index
  //background-image: https://www.toptal.com/designers/subtlepatterns/notebook/
  = render partial: "shared/display_products", locals: { meigens: @meigens }

  .pagination-footer
    = paginate(@meigens)

app/views/meigens/new.html.haml
= render partial: "shared/input_product", locals: { meigen: @meigen }

app/views/meigens/show.html.haml
.wrapper-for-meigen-show

  .meigen-show-container

    .meigen-show-container__header
      .meigen-show-container__header__information
        %ul
          %li
            = @meigen.user.name
            さんの投稿
          %li
            投稿時間:
            = @meigen.created_at
      .meigen-show-container__header__edit
        - if current_user.id == @meigen.user_id
          %ul
            %li
              = link_to "編集", edit_meigen_path(@meigen.id)
            %li
              = link_to "削除", meigen_path(@meigen.id), method: :delete

    - if @max_point.present?
      .meigen-show-container__user-possession
        %h1
          この名言は
          %span
            = @max_point[0].user.name
          さんのものです!
          %span
            = @max_point[0].value
          ポイント振っています

    .meigen-show-container__content
      .meigen-show-container__content__left
        .meigen-show-container__content__left__header
          %h1 画像
        .meigen-show-container__content__left__image.auto-icons{id: "/meigens/#{@meigen.id}"}
          = image_tag(@meigen.image)
          %p
            = @meigen.source
            の名言
      .meigen-show-container__content__right
        .meigen-show-container__content__right__header
          %h1 名言
        .meigen-show-container__content__right__meigen
          = simple_format(@meigen.content)


    .meigen-show-container__scene-content
      .meigen-show-container__scene-content__left
        .meigen-show-container__scene-content__left__header
          %h1 タグ
        .meigen-show-container__scene-content__left__tag
          - if @meigen.tag_list.length != 0
            - @meigen.tag_list.each do |tag|
              .meigen-show-container__scene-content__left__tag__name
                = tag
          - else
            .meigen-show-container__scene-content__left__tag__nothing
              %p タグ付けされていません!

      .meigen-show-container__scene-content__right
        .meigen-show-container__scene-content__right__header
          %h1 場面
        .meigen-show-container__scene-content__right__scene
          - if @meigen.scene.present?
            = simple_format(@meigen.scene)
          - else
            %p
              入力されませんでした…


    .meigen-show-container__sns-function-bar
      .meigen-show-container__sns-function-bar__box
        %ul
          %li
            #comment-counter
              %i.far.fa-comment
              = @meigen.comments_count
          %li{class: "like-heart-#{@meigen.id}"}
            = render partial: "like-view", locals: { meigen: @meigen }

    .meigen-show-container__form-box
      .meigen-show-container__form-box__point
        - if @current_status.present?
          %h1 ポイントを振り直す
        -else
          %h1 ポイントを振る
        = form_for @point, url: points_path do |f|
          = f.select :value, @num, selected: @current_point
          = f.hidden_field :meigen_id, value: @meigen.id
          = f.submit "Push", class: "point-submit-btn"
      .meigen-show-container__form-box__comment
        = form_for @comment, url: meigen_comments_path(@meigen), remote: true do |f|
          = f.text_area :content, placeholder: "コメントする", id: "comment-area"
          = f.submit "コメントする", class: "comment-submit-btn"

      .meigen-show-container__form-box__comment-index
        %h2 ＜コメント一覧＞
        - if @meigen.comments.length != 0
          = render partial: "comment-view", collection: @meigen.comments, as: "comment"
        - else
          %p.no-comment まだコメントはありません!


    %ul
      %li
        = link_to "一覧へ戻る", meigens_path
      %li
        = link_to "トップへ戻る", "/"

app/views/points/show.html.haml
.wrapper-for-meigen-index
  .my-page-header
    %h1
      = current_user.name
      さんのマイページ
    %ul
      %li
        = link_to "/users/#{current_user.id}" do
          ●投稿一覧
      %li
        = link_to "/users/#{current_user.id}/likes" do
          ●いいね一覧
      %li#point-column
        ●ポイント振った投稿一覧

    .my-page-header__remain-point
      %p
        ポイント残高：
        = current_user.point

  = render partial: "shared/display_products", locals: { meigens: @meigens }

app/views/shared/_display_products.html.haml
- meigens.each do |meigen|
  .meigen-container
    .meigen-container__header
      .meigen-container__header--information
        %ul
          %li
            投稿者：
            = meigen.user.name
          %li
            = meigen.created_at
      .meigen-container__header--access-detail
        = link_to "詳細へ", "/meigens/#{meigen.id}"
    .meigen-container__content
      .meigen-container__content__left-content
        = image_tag(meigen.image)
        .meigen-container__content__left-content__source
          = meigen.source
          の名言
        - meigen.tag_list.each do |tag|
          .meigen-container__content__left-content__tag
            = tag
      .meigen-container__content__right-content
        .meigen-container__content__right-content__meigen
          = simple_format(meigen.content)

    .meigen-container__sns-function-bar
      .meigen-container__sns-function-bar__box
        %ul
          %li
            = link_to "/meigens/#{meigen.id}" do
              %i.far.fa-comment
                = meigen.comments_count
          %li{class: "like-heart-#{meigen.id}"}
            = render partial: "meigens/like-view", locals: { meigen: meigen }


    .meigen-container__scene-displayer.accordion-btn
      %i.fas.fa-chevron-down

    .meigen-container__scene-container
      .meigen-container__scene-container__scene-text
        - if meigen.scene.present?
          = meigen.scene
        - else
          %p
            入力されませんでした…

app/views/shared/_input_product.html.haml
.wrapper
  .error-message
    - meigen.errors.full_messages.each do |message|
      = message


  .input-meigen-container
    .input-meigen-container__header
      - if controller.action_name == "edit"
        .input-meigen-container__header__information
          %ul
            %li
              = meigen.user.name
              さんの投稿
            %li
              = meigen.created_at
      - else
        %h1 名言の投稿

    = form_for meigen do |f|
      .input-meigen-container__content
        .input-meigen-container__content__left
          %h1 ◆画像の設定:
          .input-meigen-container__content__left__image
            = f.label :image do
              = fa_icon "camera", class: "camera-cursor"
              = f.file_field :image, class: "hidden"

            - if controller.action_name == "new"
              %h2 ＜プレビュー＞
              .input-meigen-container__content__left__image__preview
                %p
                  画像が未選択です
            - else
              %h2 ＜プレビュー＞
              .input-meigen-container__content__left__image__preview
                %p
                  = image_tag(meigen.image)

        .input-meigen-container__content__right
          .input-meigen-container__content__right__text
            = f.label :scene do
              %h1
                ◆名言を書く
                %span
                  (※必須)
            = f.text_area :content, placeholder: "名言を入力してください", class: "input-meigen-container__content__right__text--style"

          .input-meigen-container__content__right__source
            = f.label :source do
              %h1
                ◆誰が言ったのか
                %span
                  (※必須)
            = f.text_field :source, placeholder: "名言の出典を入力してください", class: "input-meigen-container__content__right__source--style"

          .input-meigen-container__content__right__scene
            = f.label :scene do
              %h1 ◆場面
            = f.text_area :scene, placeholder: "この名言が役立った・感動した場面を書きましょう", class: "input-meigen-container__content__right__scene--style"

          .input-meigen-container__content__tag
            = f.label :tag_list do
              %h1 ◆カンマ区切りでタグを入力
            = text_field_tag 'meigen[tag_list]', @meigen.tag_list.join(","), placeholder: "名言にタグ付けしましょう", class: "input-meigen-container__content__right__tag--style"

      - if controller.action_name == "edit"
        = f.submit "更新する", class: "input-meigen-container__submit-btn"
      - else
        = f.submit "投稿する", class: "input-meigen-container__submit-btn"

    .input-meigen-container__footer
      %ul
        %li
          = link_to "一覧へ戻る", meigens_path
        %li
          = link_to "トップへ戻る", "/"

app/views/users/show.html.haml
.wrapper-for-meigen-index
  .my-page-header
    %h1
      = current_user.name
      さんのマイページ
    %ul
      %li
        ●投稿一覧
      %li
        = link_to "/users/#{current_user.id}/likes" do
          ●いいね一覧
      %li#point-column
        = link_to "/points/#{current_user.id}" do
          ●ポイント振った投稿一覧

    .my-page-header__remain-point
      %p
        ポイント残高：
        = current_user.point

  = render partial: "shared/display_products", locals: { meigens: @meigens }